# basic options
title: JackTheRedCreeper's blog
author: GitHub User
email: your-email@domain.com
description: TTRPGs, gamedev & programming, conceptual and applied
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
