# basic options
title: JackTheRedCreeper's blog
author: JackTheRedCreeper
description: TTRPGs, gamedev & programming, conceptual and applied

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
