# basic options
title: JackTheRedCreeper's blog
author: JackTheRedCreeper
description: TTRPGs, gamedev & programming, conceptual and applied
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
